language: java
script: asdf plugin-test elasticsearch https://github.com/lowski/asdf-elasticsearch.git
before_script:
  - git clone https://github.com/asdf-vm/asdf.git
  - . asdf/asdf.sh
os:
  - linux
  - osx
